# This file was generated by GoReleaser. DO NOT EDIT.
cask "usectl" do
  name "usectl"
  desc "CLI for the usectl self-hosted deployment platform"
  homepage "https://usectl.com"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usectl"

  on_macos do
    on_intel do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_darwin_amd64.tar.gz"
      sha256 "a909e5826b0ea3e3513d9a5a5f8fb7a515af3b0d18d26638ff9fbdb34d917b4f"
    end
    on_arm do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_darwin_arm64.tar.gz"
      sha256 "5821da4a735dbc6248d8bab1c4ac6639bb5e088a95f7eaf4fb4281a5c7ed5ad0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_linux_amd64.tar.gz"
      sha256 "37bb2ffd833af6b68d871f826f0dbf0a06bb89b5883a4e1b383bebe2233f35c1"
    end
    on_arm do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_linux_arm64.tar.gz"
      sha256 "02e288f6762149476437eafb0aaf93d759e9d82e7d8778b3a79a2e8741758608"
    end
  end

  # No zap stanza required
end
