# This file was generated by GoReleaser. DO NOT EDIT.
cask "usectl" do
  name "usectl"
  desc "CLI for the usectl self-hosted deployment platform"
  homepage "https://usectl.com"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usectl"

  on_macos do
    on_intel do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_darwin_amd64.tar.gz"
      sha256 "e83923dceca4978800cbf13a1213bf4f38baa5aacacb9b2257a2d28c6bf3c848"
    end
    on_arm do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_darwin_arm64.tar.gz"
      sha256 "eba51c9a0814f689d35c87ed087b062bb7c83283120d69355577340a6f3a33b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_linux_amd64.tar.gz"
      sha256 "f450b86f85a1972d6ad90af82311b6ee6e3bee2615ea6968f810b642a55509dc"
    end
    on_arm do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_linux_arm64.tar.gz"
      sha256 "2dbff862519c8d6e2cf250aeaedea79cd77e89207415f06af69f7c72cd2976af"
    end
  end

  # No zap stanza required
end
