# This file was generated by GoReleaser. DO NOT EDIT.
cask "usectl" do
  name "usectl"
  desc "CLI for the usectl self-hosted deployment platform"
  homepage "https://usectl.com"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usectl"

  on_macos do
    on_intel do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_darwin_amd64.tar.gz"
      sha256 "202ff9dd468b7b1ac2fb94a040b6b7c9ae6ab2a4d21a8235ad25a61a7052621d"
    end
    on_arm do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_darwin_arm64.tar.gz"
      sha256 "c5eacb26214cebc677a42cec6c08435b30494b956f817a3b01d29f6ef72ef113"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_linux_amd64.tar.gz"
      sha256 "20c4f23e3938c49fb136fd86dd9a8004a8ba6e4c397bcee7e2b5e7dea6ee6fd4"
    end
    on_arm do
      url "https://github.com/syst3mctl/usectl-cli/releases/download/v#{version}/usectl_#{version}_linux_arm64.tar.gz"
      sha256 "5f27fe67474e1cc901cbe75a5a38e1f151c02470dbdcd7cb0e2cfbf6dd75f8ea"
    end
  end

  # No zap stanza required
end
