package cmd

import (
	"fmt"
	"sort"
	"strings"

	"github.com/giorgi/usectl/output"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// `usectl schema` — the whole command surface as one machine-readable document.
//
// Written for AI agents and scripts. Without it, discovering the CLI means
// recursively shelling out to `--help` for every command and parsing prose;
// this returns the same information already structured, in a single call.
//
// It is generated by walking the live cobra tree, so it cannot drift from the
// implementation the way a hand-maintained reference does (CLI-REFERENCE.md
// went stale exactly that way).

type schemaFlag struct {
	Name      string `json:"name"`
	Shorthand string `json:"shorthand,omitempty"`
	Type      string `json:"type"`
	Default   string `json:"default,omitempty"`
	Usage     string `json:"usage,omitempty"`
	// Inherited marks a flag that comes from a parent command (--json,
	// --machine, ...) rather than being declared on this one.
	Inherited bool `json:"inherited,omitempty"`
}

type schemaCommand struct {
	Path        string          `json:"path"`
	Use         string          `json:"use"`
	Short       string          `json:"short,omitempty"`
	Long        string          `json:"long,omitempty"`
	Aliases     []string        `json:"aliases,omitempty"`
	Example     string          `json:"example,omitempty"`
	Runnable    bool            `json:"runnable"`
	Args        string          `json:"args,omitempty"`
	Flags       []schemaFlag    `json:"flags,omitempty"`
	Subcommands []schemaCommand `json:"subcommands,omitempty"`
}

type schemaDoc struct {
	Tool     string          `json:"tool"`
	Version  string          `json:"version"`
	APIURL   string          `json:"api_url"`
	Notes    schemaNotes     `json:"notes"`
	Commands []schemaCommand `json:"commands"`
}

// schemaNotes carries the few rules that are not derivable from the command
// tree but that an agent must know to drive the CLI correctly.
type schemaNotes struct {
	MachineResolution   []string `json:"machine_resolution"`
	NonInteractive      string   `json:"non_interactive"`
	JSONOutput          string   `json:"json_output"`
	NamingModel         string   `json:"naming_model"`
	DestructiveCommands []string `json:"destructive_commands"`
}

var schemaCmd = &cobra.Command{
	Use:   "schema",
	Short: "Print the full command tree as JSON (for scripts and AI agents)",
	Long: `Emit every command, alias, argument shape and flag as a single JSON document.

Intended for automation: one call replaces recursively scraping --help. The
document is generated from the live command tree, so it always matches the
binary that produced it.

Without --json the same tree is printed as an indented outline.`,
	Example: `  usectl schema --json
  usectl schema --json | jq '.commands[] | select(.path=="usectl machines") | .subcommands[].path'
  usectl schema`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		doc := schemaDoc{
			Tool:    "usectl",
			Version: Version,
			APIURL:  apiURL,
			Notes: schemaNotes{
				MachineResolution: []string{
					"A machine may be named by its name, its UUID, or an unambiguous UUID prefix.",
					"Precedence, highest first: explicit positional argument; -m/--machine; $USECTL_MACHINE; the default saved by 'usectl use'.",
					"When a machine is resolved from anything other than an explicit argument, the source is echoed to stderr.",
				},
				NonInteractive: "Commands that would prompt (machines create, machines pods create, machines addons add) never prompt when --json or --yes is set, or when stdin is not a terminal. They exit non-zero listing the missing flags.",
				JSONOutput:     "--json is accepted by every command and disables colour. Errors go to stderr; the exit code is non-zero on failure.",
				NamingModel:    "A MACHINE is a namespace plus a vCPU/RAM/storage quota and one subscription; it holds no code. A POD is one workload inside a machine and owns repo/branch or image, domain, ports, visibility, limits and rollout strategy. Addons are provisioned per machine and must be ATTACHED to a pod before that pod receives their env vars.",
				DestructiveCommands: []string{
					"usectl machines delete",
					"usectl machines addons remove",
					"usectl machines pods delete",
					"usectl machines groups delete",
				},
			},
		}
		for _, c := range rootCmd.Commands() {
			if c.Hidden || c.Name() == "help" || c.Name() == "completion" {
				continue
			}
			doc.Commands = append(doc.Commands, describeCommand(c))
		}
		sort.Slice(doc.Commands, func(i, j int) bool { return doc.Commands[i].Path < doc.Commands[j].Path })

		if jsonOutput {
			return output.JSON(doc)
		}
		for _, c := range doc.Commands {
			printSchemaOutline(c, 0)
		}
		fmt.Println("\nPass --json for the full machine-readable document.")
		return nil
	},
}

func describeCommand(c *cobra.Command) schemaCommand {
	sc := schemaCommand{
		Path:     c.CommandPath(),
		Use:      c.Use,
		Short:    c.Short,
		Long:     c.Long,
		Aliases:  c.Aliases,
		Example:  strings.TrimSpace(c.Example),
		Runnable: c.Runnable(),
		Args:     argShape(c),
	}
	c.NonInheritedFlags().VisitAll(func(f *pflag.Flag) {
		sc.Flags = append(sc.Flags, describeFlag(f, false))
	})
	c.InheritedFlags().VisitAll(func(f *pflag.Flag) {
		sc.Flags = append(sc.Flags, describeFlag(f, true))
	})
	sort.Slice(sc.Flags, func(i, j int) bool { return sc.Flags[i].Name < sc.Flags[j].Name })

	for _, sub := range c.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		sc.Subcommands = append(sc.Subcommands, describeCommand(sub))
	}
	sort.Slice(sc.Subcommands, func(i, j int) bool { return sc.Subcommands[i].Path < sc.Subcommands[j].Path })
	return sc
}

func describeFlag(f *pflag.Flag, inherited bool) schemaFlag {
	return schemaFlag{
		Name:      f.Name,
		Shorthand: f.Shorthand,
		Type:      f.Value.Type(),
		Default:   f.DefValue,
		Usage:     f.Usage,
		Inherited: inherited,
	}
}

// argShape reports the positional-argument contract. Cobra keeps this as an
// opaque validator func with no introspection, so it is recovered from the
// Use line — which is the same string the command's help shows, and is
// therefore the thing that must be kept accurate anyway.
func argShape(c *cobra.Command) string {
	fields := strings.Fields(c.Use)
	if len(fields) <= 1 {
		return ""
	}
	return strings.Join(fields[1:], " ")
}

func printSchemaOutline(c schemaCommand, depth int) {
	indent := strings.Repeat("  ", depth)
	name := c.Path
	if depth > 0 {
		name = strings.Fields(c.Path)[len(strings.Fields(c.Path))-1]
	}
	line := indent + output.Bold(name)
	if c.Args != "" {
		line += " " + output.Dim(c.Args)
	}
	fmt.Printf("%s\n", line)
	if c.Short != "" {
		fmt.Printf("%s  %s\n", indent, output.Dim(c.Short))
	}
	for _, sub := range c.Subcommands {
		printSchemaOutline(sub, depth+1)
	}
}

func init() {
	rootCmd.AddCommand(schemaCmd)
}
